#!/usr/bin/env python3
"""
masumi_verifier_adapter.py — MIP-003 & MIP-004 Agentic Service Adapter
Exposes AI Fact & Web Content Verification to Masumi & Sokosumi Marketplace.
Standard Endpoints:
  - GET  /availability
  - GET  /input_schema
  - POST /start_job
  - GET  /status
  - GET  /demo
"""

import os
import sys
import time
import uuid
import json
import hashlib
import asyncio
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Any, List, Optional

import uvicorn
from fastapi import FastAPI, HTTPException, Query
from pydantic import BaseModel, Field

# Ensure verify-api module resolution
VERIFY_API_DIR = Path("/home/aether/verify-api")
if str(VERIFY_API_DIR) not in sys.path:
    sys.path.insert(0, str(VERIFY_API_DIR))

# Import local engines
try:
    import main as verify_engine
    import reader_backend
except ImportError as e:
    raise RuntimeError(f"Cannot import verify-api engine: {e}")

app = FastAPI(
    title="Masumi MIP-003 AI Verifier & Web Reader",
    description="Agentic service adapter compliant with Masumi MIP-003 and MIP-004 standards.",
    version="1.0.0"
)

# In-memory Job Store (MIP-003 requires tracking lifecycle)
JOBS: Dict[str, Dict[str, Any]] = {}
START_TIME = time.time()

# Models
class InputDataItem(BaseModel):
    key: str
    value: str

class StartJobRequest(BaseModel):
    input_data: List[InputDataItem]
    identifier_from_purchaser: str = Field(..., description="Unique ID generated by the buyer/marketplace")

class StartJobResponse(BaseModel):
    job_id: str
    identifier_from_seller: str
    blockchain_identifier: str
    payment_address: str
    amount_lovelace: int
    status: str

# Helper: RFC 8785 Canonical JSON & Decision Hash (MIP-004)
def canonical_dumps(data: Any) -> str:
    """Canonicalize JSON per RFC 8785 rules (sorted keys, compact separators)."""
    return json.dumps(data, sort_keys=True, separators=(",", ":"), ensure_ascii=False)

def compute_hashes(identifier_from_purchaser: str, input_data: Any, output_data: Any):
    canonical_input = canonical_dumps(input_data)
    canonical_output = canonical_dumps(output_data)
    
    in_str = f"{identifier_from_purchaser};{canonical_input}"
    out_str = f"{identifier_from_purchaser};{canonical_output}"
    
    in_hash = hashlib.sha256(in_str.encode("utf-8")).hexdigest()
    out_hash = hashlib.sha256(out_str.encode("utf-8")).hexdigest()
    decision_hash = in_hash + out_hash
    return in_hash, out_hash, decision_hash

# Background Task: Worker to execute job
async def execute_job(job_id: str, mode: str, params: Dict[str, Any], identifier_from_purchaser: str):
    job = JOBS.get(job_id)
    if not job:
        return

    job["status"] = "running"
    job["progress"] = {"current_step": "Processing request", "percentage": 30}
    t0 = time.time()

    try:
        output_result = {}
        if mode == "read_web":
            url = str(params.get("url") or params.get("target_url") or "")
            job["progress"] = {"current_step": f"Extracting {url}", "percentage": 60}
            res = await reader_backend.extract_url(
                url=url,
                include_links=bool(params.get("include_links", True)),
                include_images=bool(params.get("include_images", False))
            )
            output_result = res

        else: # verify_claim or probe
            query = params.get("query", "")
            req_type = params.get("type", "claim_verify")
            target_url = params.get("target_url")
            
            job["progress"] = {"current_step": "Analyzing claim & probing evidence", "percentage": 60}
            req = verify_engine.Req(
                query=query,
                type=req_type,
                depth=params.get("depth", "standard"),
                target_url=target_url
            )
            res = await verify_engine.verify(req)
            output_result = res

        elapsed = round(time.time() - t0, 2)
        in_hash, out_hash, dec_hash = compute_hashes(identifier_from_purchaser, params, output_result)

        job["status"] = "completed"
        job["output"] = output_result
        job["input_hash"] = in_hash
        job["output_hash"] = out_hash
        job["decision_hash"] = dec_hash
        job["execution_time_seconds"] = elapsed
        job["progress"] = {"current_step": "Done", "percentage": 100}

    except Exception as e:
        job["status"] = "failed"
        job["error"] = "PROCESSING_ERROR"
        job["message"] = str(e)[:300]
        job["execution_time_seconds"] = round(time.time() - t0, 2)


# =====================================================================
# MIP-003 Standard Endpoints
# =====================================================================

@app.get("/availability")
async def get_availability():
    """MIP-003: Health and operational load check."""
    uptime = int(time.time() - START_TIME)
    active = sum(1 for j in JOBS.values() if j.get("status") in ("awaiting_payment", "running"))
    return {
        "status": "available",
        "message": "AI Fact & Web Content Verifier ready",
        "uptime_seconds": uptime,
        "current_load": {
            "active_jobs": active,
            "queued_jobs": 0,
            "max_capacity": 50
        }
    }

@app.get("/input_schema")
async def get_input_schema():
    """MIP-003: Defines acceptable inputs for /start_job."""
    return {
        "type": "object",
        "properties": {
            "mode": {
                "type": "string",
                "enum": ["verify_claim", "read_web"],
                "default": "verify_claim",
                "description": "'verify_claim' for tech & AI claim checks, 'read_web' for anti-bot clean markdown extraction."
            },
            "query": {
                "type": "string",
                "description": "Claim or question to verify (required if mode=verify_claim)."
            },
            "target_url": {
                "type": "string",
                "description": "Target webpage URL (required if mode=read_web, optional for endpoint_check)."
            },
            "type": {
                "type": "string",
                "enum": ["claim_verify", "endpoint_check", "pricing_check", "region_check", "error_diagnosis"],
                "default": "claim_verify"
            },
            "depth": {
                "type": "string",
                "enum": ["standard", "deep"],
                "default": "standard"
            }
        },
        "required": ["mode"]
    }

@app.post("/start_job", response_model=StartJobResponse)
async def start_job(payload: StartJobRequest):
    """MIP-003: Initiate a new job."""
    # Convert input_data array [{key, value}] to dict
    params = {}
    for item in payload.input_data:
        params[item.key] = item.value

    mode = params.get("mode", "verify_claim")
    if mode == "verify_claim" and not params.get("query") and not params.get("target_url"):
        raise HTTPException(status_code=400, detail="INVALID_INPUT: 'query' or 'target_url' required for verify_claim.")
    if mode == "read_web" and not params.get("target_url"):
        raise HTTPException(status_code=400, detail="INVALID_INPUT: 'target_url' required for read_web.")

    job_id = f"job-{uuid.uuid4().hex[:12]}"
    seller_id = f"seller-{job_id}"
    
    # In live testnet, blockchain_identifier and payment_address come from Masumi Payment Service
    # Here we mock standard Preprod testnet response until local Payment Service node is linked
    mock_blockchain_id = f"cardano-tx-{uuid.uuid4().hex[:16]}"
    mock_preprod_address = "addr_test1vrm0e7q3d98h6swr2juxk9c424sq7dflz2n4yqqc7n695ggu5g630"
    price_lovelace = 5_000_000  # 5 tADA (~100 credits)

    job_entry = {
        "job_id": job_id,
        "identifier_from_seller": seller_id,
        "identifier_from_purchaser": payload.identifier_from_purchaser,
        "blockchain_identifier": mock_blockchain_id,
        "payment_address": mock_preprod_address,
        "amount_lovelace": price_lovelace,
        "status": "awaiting_payment",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "mode": mode,
        "params": params
    }
    JOBS[job_id] = job_entry

    # For testing / demo without immediate payment hook: auto-trigger background worker
    # In live Masumi production, this trigger happens upon 'FundsLocked' event.
    asyncio.create_task(execute_job(job_id, mode, params, payload.identifier_from_purchaser))

    return StartJobResponse(
        job_id=job_id,
        identifier_from_seller=seller_id,
        blockchain_identifier=mock_blockchain_id,
        payment_address=mock_preprod_address,
        amount_lovelace=price_lovelace,
        status="awaiting_payment"
    )

@app.get("/status")
async def get_status(job_id: str = Query(..., description="Job ID returned by /start_job")):
    """MIP-003: Poll job status, results, and cryptographic hashes."""
    job = JOBS.get(job_id)
    if not job:
        raise HTTPException(status_code=404, detail="JOB_NOT_FOUND")

    status = job.get("status")

    if status == "awaiting_payment":
        return {
            "job_id": job_id,
            "status": "awaiting_payment",
            "payment_address": job["payment_address"],
            "amount_lovelace": job["amount_lovelace"]
        }
    elif status == "running":
        return {
            "job_id": job_id,
            "status": "running",
            "progress": job.get("progress", {"current_step": "In progress", "percentage": 50})
        }
    elif status == "completed":
        return {
            "job_id": job_id,
            "status": "completed",
            "output": job.get("output"),
            "input_hash": job.get("input_hash"),
            "output_hash": job.get("output_hash"),
            "decision_hash": job.get("decision_hash"),
            "execution_time_seconds": job.get("execution_time_seconds")
        }
    elif status == "failed":
        return {
            "job_id": job_id,
            "status": "failed",
            "error": job.get("error", "PROCESSING_ERROR"),
            "message": job.get("message", "Job processing failed.")
        }
    
    return {"job_id": job_id, "status": status}

@app.get("/demo")
async def get_demo():
    """Optional MIP-003 endpoint for Sokosumi marketplace preview."""
    return {
        "input_sample": [
            {"key": "mode", "value": "verify_claim"},
            {"key": "query", "value": "Is Base network transaction settled on Ethereum L1?"},
            {"key": "type", "value": "claim_verify"}
        ],
        "output_sample": {
            "verdict": "TRUE",
            "answer": "Base is an Ethereum Layer 2 network built on the OP Stack, settling transactions periodically to Ethereum L1.",
            "confidence": 0.95,
            "sources": [{"url": "https://docs.base.org", "type": "official"}]
        }
    }

if __name__ == "__main__":
    uvicorn.run("masumi_verifier_adapter:app", host="0.0.0.0", port=8086, reload=False)
